# Generated by Django 3.0.7 on 2020-09-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('files', models.FileField(blank=True, null=True, upload_to='activities')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=40, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(max_length=20)),
                ('question1', models.CharField(blank=True, max_length=20, null=True)),
                ('question2', models.CharField(blank=True, max_length=20, null=True)),
                ('question3', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic', to='tbcomp_app.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Uploaded', 'Uploaded'), ('Rejected', 'Rejected')], max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentUpload', to='tbcomp_app.Activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentUpload', to='tbcomp_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('files', models.FileField(blank=True, null=True, upload_to='files')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Document', to='tbcomp_app.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activity', to='tbcomp_app.Topic'),
        ),
    ]
