# Generated by Django 3.0.8 on 2020-08-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbcomp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullname',
        ),
    ]
