# Generated by Django 2.2.14 on 2020-07-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbcomp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullName',
        ),
    ]
