# Generated by Django 3.0.7 on 2020-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcomp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='driveLink',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
