# Generated by Django 3.0.7 on 2020-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcomp_app', '0002_auto_20200728_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='question1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='question2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='question3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
