# Generated by Django 3.0.8 on 2020-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcomp_app', '0002_auto_20200816_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
