# Generated by Django 3.0.8 on 2020-09-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbcomp_app', '0003_auto_20200816_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentupload',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='studentupload',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Uploaded', 'Uploaded'), ('Rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
